services:
  - type: web
    name: signature-verification
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: PYTORCH_CPU_ONLY
        value: "1"
    autoDeploy: true
    healthCheckPath: /health
    disk:
      name: model-storage
      mountPath: /opt/render/project/src
      sizeGB: 1